name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm --prefix ./store-pro install
      - run: npm --prefix ./store-pro-angular/test install
      - run: npm --prefix ./store-pro-angular install
      - run: npm --prefix ./store-pro-react install
      - run: npm --prefix ./store-pro-svelte install
      - run: npm --prefix ./store-pro run build-test
      - run: npm --prefix ./store-pro-react run build-test
      - run: npm --prefix ./store-pro-svelte run test
      - run: npm --prefix ./store-pro-angular run build-test
